### ISSUE TITLE
Question about thread safety guarantees

### ISSUE THREAD

**Issue by xgcssch** [at-wat/mqtt-go#144]
Hello!

I have two questions about the thread safety of the various types:
- Can a `mqtt.Client` be used from multiple threads without synchronization? E. g. one routine which handles subscriptions via `mqtt.ServeMux` and multiple other routines doing `Publish`?
- If no: can a `mqtt.URLDialer` be shared between multiple `mqtt.Client`?

Thanks!
Sönke

**Comment by at-wat** [comment]
> Can a `mqtt.Client` be used from multiple threads without synchronization? E. g. one routine which handles subscriptions via `mqtt.ServeMux` and multiple other routines doing `Publish`?

All `mqtt.Client` interface implementations in mqtt-go package (`*BaseClient`, `*RetryClient`, `ReconnectClient`) should be thread safe.
(They internally have mutex.)

> If no: can a `mqtt.URLDialer` be shared between multiple `mqtt.Client`?

`mqtt.URLDialer` can be shared. It doesn't have any internal state.

**Comment by xgcssch** [comment]
Thanks much for the clarification!
Maybe you should incorporate that into the documentation!
Stay safe!
Sönke
