### ISSUE TITLE
Problem when trying to disconnect then reconnect 

### ISSUE THREAD

**Issue by YannickRiou** [at-wat/mqtt-go#199]
I am using mqtt-go in the scope of this module https://github.com/seqsense/aws-iot-device-sdk-go. 

I manage to create a connection and to communicate through mqtt. But when I try to call the disconnect function and then after some time , call the connect function, I get this error : 

```
panic: close of closed channel

goroutine 18 [running]:
github.com/at-wat/mqtt-go.(*reconnectClient).Connect.func1.1()
        C:/Users/Ingénieur Systèmes/go/pkg/mod/github.com/at-wat/mqtt-go@v0.16.0/reconnclient.go:86 +0x25
github.com/at-wat/mqtt-go.(*reconnectClient).Connect.func1({0x1021310, 0xc000024300})
        C:/Users/Ingénieur Systèmes/go/pkg/mod/github.com/at-wat/mqtt-go@v0.16.0/reconnclient.go:144 +0x7f5
created by github.com/at-wat/mqtt-go.(*reconnectClient).Connect
        C:/Users/Ingénieur Systèmes/go/pkg/mod/github.com/at-wat/mqtt-go@v0.16.0/reconnclient.go:84 +0x31e
exit status 2
```

Here is the context : 

The connection is created like this with the above module : 

```
cli, err := awsiotdev.New(
		thingName,
		&mqtt.URLDialer{
			URL: fmt.Sprintf("tls://%s:8883", host),
			Options: []mqtt.DialOption{
				mqtt.WithTLSCertFiles(
					host,
					"./cert/root.ca.pem",
					"./cert/xxxxx-certificate.pem.crt",
					"./cert/xxxxx-private.pem.key",
				),
				mqtt.WithConnStateHandler(func(s mqtt.ConnState, err error) {
					fmt.Printf("Connection State Handler [%s]: %v\n", s, err)
				}),
			},
		},
		//mqtt.WithReconnectWait(500*time.Millisecond, 2*time.Second),
	)
	if err != nil {
		panic(err)
	}

	// Multiplex message handler to route messages to multiple features.
	var mux mqtt.ServeMux
	cli.Handle(&mux)

```

The new function from awsiotdev (seqsense/aws-iot-device-sdk-go) creates a mqtt reconnect client, so the disconnect/reconnect should work : 

```
// New creates AWS IoT device interface.
func New(thingName string, dialer mqtt.Dialer, opts ...mqtt.ReconnectOption) (Device, error) {
	cli, err := mqtt.NewReconnectClient(dialer, opts...)
	if err != nil {
		return nil, ioterr.New(err, "creating MQTT connection")
	}
	return &device{
		ReconnectClient: cli,
		thingName:       thingName,
	}, nil
}
```

And the connection/deconnection scenario is as follow : 
```
if _, err := cli.Connect(ctx,
		thingName,
		mqtt.WithKeepAlive(30),
	); err != nil {
		panic(err)
	}

	time.Sleep(time.Second)

	errDisc := cli.Disconnect(ctx)
	if errDisc != nil {
		panic(err)
	}

	if _, err := cli.Connect(ctx,         <<----- The problem happen here 
		thingName,
	); err != nil {
		panic(err)
	}

	time.Sleep(time.Second)
```

What is the right way to close a connection then open it again ? 

Thanks in advance

**Comment by at-wat** [comment]
@YannickRiou thank you for the detailed report!

Originally, I designed the client interface as a direct representation (as much as possible) of MQTT protocol, so reusing `Disconnect`-ed client is not considered since the server must close TCP connection after `Disconnect` and client should dial again to `Connect` again.
On the current version, client should be recreated to `Connect` after `Disconnect`.

For `RetryClient` and `ReconnectClient`, it might be good to support `Connect` after `Disconnect` if there are use cases requiring it.

What is your use case of `Disconnect` and `Connect` using same client?

**Comment by YannickRiou** [comment]
Thank you at-wat and akupila for your enlightments ! It's now clear !
